const data = [
  {
    id: 1,
    name: "Badminton Raquet",
    image_src: "./badminton.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 5000,
    quantity: 1,
    incart: false,
  },
  {
    id: 2,
    name: "Badminton Raquet",
    image_src: "./badminton.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 5000,
    quantity: 1,
    incart: false,
  },

  {
    id: 3,
    name: "Badminton Raquet",
    image_src: "./badminton.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 5000,
    quantity: 1,
    incart: false,
  },
  {
    id: 4,
    name: "Badminton Raquet",
    image_src: "./badminton.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 5000,
    quantity: 1,
    incart: false,
  },
  {
    id: 5,
    name: "Badminton Raquet",
    image_src: "./badminton.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 5000,
    quantity: 1,
    incart: false,
  },

  {
    id: 6,
    name: "Badminton Raquet",
    image_src: "./badminton.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 5000,
    quantity: 1,
    incart: false,
  },
  {
    id: 7,
    name: "Badminton Raquet",
    image_src: "./badminton.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 5000,
    quantity: 1,
    incart: false,
  },
  {
    id: 8,
    name: "Badminton Raquet",
    image_src: "./badminton.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 5000,
    quantity: 1,
    incart: false,
  },

  {
    id: 9,
    name: "Badminton Raquet",
    image_src: "./badminton.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 5000,
    quantity: 1,
    incart: false,
  },
  {
    id: 10,
    name: "Badminton Raquet",
    image_src: "./badminton.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 5000,
    quantity: 1,
    incart: false,
  },
  {
    id: 11,
    name: "Badminton Raquet",
    image_src: "./badminton.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 5000,
    quantity: 1,
    incart: false,
  },

  {
    id: 12,
    name: "Badminton Raquet",
    image_src: "./badminton.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 5000,
    quantity: 1,
    incart: false,
  },
  {
    id: 13,
    name: "Product1",
    image_src: "./1.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 2000,
    quantity: 1,
    incart: false,
  },
  {
    id: 14,
    name: "Product2",
    image_src: "./2.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 1500,
    quantity: 1,
    incart: false,
  },

  {
    id: 15,
    name: "Product3",
    image_src: "./1.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 1000,
    quantity: 1,
    incart: false,
  },
  {
    id: 16,
    name: "SOFA",
    image_src: "./f1.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
  {
    id: 17,
    name: "TABLE",
    image_src: "./f2.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
  {
    id: 18,
    name: "DINING",
    image_src: "./f3.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
  {
    id: 19,
    name: "SOFA",
    image_src: "./f1.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
  {
    id: 20,
    name: "TABLE",
    image_src: "./f2.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
  {
    id: 21,
    name: "GROCERY",
    image_src: "./f3.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
  {
    id: 22,
    name: "GROCERY",
    image_src: "./f3.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
  {
    id: 23,
    name: "GROCERY",
    image_src: "./f3.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
  {
    id: 24,
    name: "GROCERY",
    image_src: "./f3.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
  {
    id: 25,
    name: "GROCERY",
    image_src: "./f3.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
  {
    id: 26,
    name: "GROCERY",
    image_src: "./f3.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
  {
    id: 27,
    name: "GROCERY",
    image_src: "./f3.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
  {
    id: 28,
    name: "GROCERY",
    image_src: "./f3.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
  {
    id: 29,
    name: "GROCERY",
    image_src: "./f3.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
  {
    id: 30,
    name: "GROCERY",
    image_src: "./f3.jpeg",
    seller: "Sunrise pvt. ltd.",
    category: "Sports",
    price: 70000,
    quantity: 1,
    incart: false,
  },
];

export default data;